version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: daiichi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1