import { RiskAssessment } from '@/types/risk-assessment';

export const mockRiskAssessments: RiskAssessment[] = [
  {
    id: 1,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "事故.xlsx",
    reference: "事故.xlsx",
    hazard: "足を踏み外して転落する危険性がある。",
    riskReduction: "作業台の設置状況を点検し、二人以上で作業を行い、経験の浅い作業員は指導者のもとで作業する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 4,
    riskScoreAfter: 17,
    riskLevelAfter: "IV",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20"
  },
  {
    id: 2,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "2025年2月14日朝礼.txt",
    reference: "2025年2月14日朝礼.txt",
    hazard: "車両との接触や転倒、足元不良による怪我が発生する可能性がある。",
    riskReduction: "安全靴・ヘルメットを着用し、車両の動きに注意して誘導員を配置し、足元の安全を確認する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 4,
    riskScore: 14,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 3,
    riskScoreAfter: 10,
    riskLevelAfter: "III",
    createdAt: "2024-01-16",
    updatedAt: "2024-01-21"
  },
  {
    id: 3,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "日東電工　保守リスクアセスメント R0 YN 250516.xlsx",
    reference: "日東電工　保守リスクアセスメント R0 YN 250516.xlsx",
    hazard: "ケージや移載機と作業者・物品との挟まれや衝突が発生する可能性がある。",
    riskReduction: "原点復帰動作を低速化し、動作パターンを最適化し、警報装置や侵入検知センサーと連動した一時停止機能を設け、動作範囲の人や物の確認、声掛け合図、監視員配置、原点復帰ボタン3秒長押しを徹底する。",
    measureType: "工学的対策",
    severity: 6,
    probability: 4,
    exposure: 4,
    riskScore: 14,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 9,
    riskLevelAfter: "III",
    createdAt: "2024-01-17",
    updatedAt: "2024-01-22"
  },
  {
    id: 4,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "as2024_2449_00.pdf",
    reference: "as2024_2449_00.pdf",
    hazard: "酸欠などによる窒息事故が発生する可能性がある。",
    riskReduction: "酸素濃度を測定し、換気を徹底し、保護具を着用する。",
    measureType: "個人用保護具",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 1,
    riskScoreAfter: 12,
    riskLevelAfter: "IV",
    createdAt: "2024-01-18",
    updatedAt: "2024-01-23"
  },
  {
    id: 5,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "2025年2月14日朝礼.pdf",
    reference: "2025年2月14日朝礼.pdf",
    hazard: "他車両や作業員との接触事故や交通の妨げによる二次災害が発生する可能性がある。",
    riskReduction: "誘導員を配置し、反射ベストを着用し、周囲の安全確認を徹底し、必要に応じて一時的な通行止めを実施する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 4,
    riskScore: 14,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 9,
    riskLevelAfter: "III",
    createdAt: "2024-01-19",
    updatedAt: "2024-01-24"
  },
  {
    id: 6,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "現地ATKYの実施時に作業手順の確認不足により誤った作業を行う可能性がある。",
    riskReduction: "作業開始前に全員で手順書を確認し、疑問点があればその場で解消する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 3,
    riskScore: 13,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 3,
    riskScoreAfter: 10,
    riskLevelAfter: "III",
    createdAt: "2024-01-20",
    updatedAt: "2024-01-25"
  },
  {
    id: 7,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "現地ATKYの実施時に周囲の危険要因を見落とすことで事故が発生する可能性がある。",
    riskReduction: "現地でのKY活動時に全員で周囲の危険要因を指差し呼称しながら確認する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 6,
    exposure: 4,
    riskScore: 16,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 3,
    exposureAfter: 3,
    riskScoreAfter: 12,
    riskLevelAfter: "IV",
    createdAt: "2024-01-21",
    updatedAt: "2024-01-26"
  },
  {
    id: 8,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "現地ATKYの実施時にコミュニケーション不足により情報共有が不十分となる可能性がある。",
    riskReduction: "作業前に全員で意見交換を行い、役割分担や注意事項を明確にする。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 3,
    riskScore: 13,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 3,
    exposureAfter: 3,
    riskScoreAfter: 12,
    riskLevelAfter: "IV",
    createdAt: "2024-01-22",
    updatedAt: "2024-01-27"
  },
  {
    id: 9,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "現地ATKYの実施時に天候や環境変化により新たな危険が発生する可能性がある。",
    riskReduction: "天候や現場環境の変化があれば都度ATKYを再実施し、危険要因を再確認する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 3,
    riskScore: 13,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 11,
    riskLevelAfter: "III",
    createdAt: "2024-01-23",
    updatedAt: "2024-01-28"
  },
  {
    id: 10,
    work: "現地ATKYの実施",
    workElement: "現地ATKYを実施する",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "現地ATKYの実施時に時間に追われて十分なリスクアセスメントが行われない可能性がある。",
    riskReduction: "作業開始前に十分な時間を確保し、焦らずにATKYを実施するよう指導する。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 3,
    riskScore: 13,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 11,
    riskLevelAfter: "III",
    createdAt: "2024-01-24",
    updatedAt: "2024-01-29"
  },
  {
    id: 11,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "リスクアセスメント抽出例_250413.gdoc",
    reference: "リスクアセスメント抽出例_250413.gdoc",
    hazard: "ハーネスの不適切な装着やフックの掛け損じによって作業者が墜落する可能性がある。",
    riskReduction: "規格に適合したフルハーネスとランヤードを使用し、視認しやすいアンカーポイントを設置したうえで、装着や取付方法について教育を徹底する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-01-25",
    updatedAt: "2024-01-30"
  },
  {
    id: 12,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "20090317_Y4AMHS工事トラブル報告(足場ブレス落下)ATJ北尾追記.pdf",
    reference: "20090317_Y4AMHS工事トラブル報告(足場ブレス落下)ATJ北尾追記.pdf",
    hazard: "高所作業中に作業者が墜落・転落したり、工具や部材が落下して負傷する恐れがある。",
    riskReduction: "安全帯や墜落制止用器具を着用し、工具や部材の落下防止措置を講じ、作業エリア下部への立入を禁止する。",
    measureType: "工学的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-01-26",
    updatedAt: "2024-01-31"
  },
  {
    id: 13,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "000664303.pdf",
    reference: "000664303.pdf",
    hazard: "手摺など取付設備の強度が不足している場合、墜落時に設備が破損・脱落し、作業者が墜落する危険がある。",
    riskReduction: "取付設備の強度が十分か事前に確認し、不明な場合は使用を避け、やむを得ず使用する場合はできる限り高い位置に取り付ける。",
    measureType: "設計時対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 4,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-01-27",
    updatedAt: "2024-02-01"
  },
  {
    id: 14,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "20230321  漏電エラー（シャフト内工事）.pdf",
    reference: "20230321  漏電エラー（シャフト内工事）.pdf",
    hazard: "重量物の落下や手指の挟まれ、転倒などによって作業者が負傷する可能性がある。",
    riskReduction: "作業前に吊り具やチェーンブロックの点検を行い、適切な保護具（ヘルメット・手袋）を着用し、2人以上で作業し、作業エリアの安全を確保する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 4,
    exposure: 4,
    riskScore: 18,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 11,
    riskLevelAfter: "III",
    createdAt: "2024-01-28",
    updatedAt: "2024-02-02"
  },
  {
    id: 15,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "【書式ルール解除】リスクアセスメントシート  YN 250409.xlsx",
    reference: "【書式ルール解除】リスクアセスメントシート  YN 250409.xlsx",
    hazard: "フレーム接続箇所に体や手、指を挿れたままフレームを下降させた場合、挟まれる危険がある。",
    riskReduction: "どの箇所が接続箇所となるかを事前に確認し、その箇所に手や指を入れないようにする。",
    measureType: "管理的対策",
    severity: 6,
    probability: 4,
    exposure: 3,
    riskScore: 13,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 3,
    riskScoreAfter: 10,
    riskLevelAfter: "III",
    createdAt: "2024-01-29",
    updatedAt: "2024-02-03"
  },
  {
    id: 16,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "手摺の腐食や損傷によってハーネスフックが外れることで墜落する危険がある。",
    riskReduction: "手摺の状態を作業前に点検し、腐食や損傷が認められる場合は使用を中止する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 4,
    exposure: 3,
    riskScore: 17,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 13,
    riskLevelAfter: "IV",
    createdAt: "2024-01-30",
    updatedAt: "2024-02-04"
  },
  {
    id: 17,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "シャフト内の狭隘空間での作業により、バランスを崩して転倒や墜落する可能性がある。",
    riskReduction: "作業前に足場や作業スペースの安全を確認し、必要に応じて補助者を配置する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 4,
    exposure: 4,
    riskScore: 18,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 13,
    riskLevelAfter: "IV",
    createdAt: "2024-01-31",
    updatedAt: "2024-02-05"
  },
  {
    id: 18,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "ハーネスフックの掛け替え時に一時的に無保護状態となり、墜落するリスクがある。",
    riskReduction: "ダブルランヤードを使用し、常にどちらか一方が確実に固定されている状態を保つ。",
    measureType: "工学的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-06"
  },
  {
    id: 19,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "手摺の形状や設置状況が不適切で、フックが正しく掛からず外れる危険がある。",
    riskReduction: "フックが確実に掛かる形状・寸法の手摺を選定し、設置状況を事前に確認する。",
    measureType: "設計時対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-02",
    updatedAt: "2024-02-07"
  },
  {
    id: 20,
    work: "ハーネスフックの取付け",
    workElement: "４Fシャフト内既設の手摺にハーネスフックを掛ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "作業中に他の作業者が接触し、バランスを崩して墜落する可能性がある。",
    riskReduction: "作業エリアへの立入制限を設け、作業者同士の接触を防止する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-03",
    updatedAt: "2024-02-08"
  },
  {
    id: 21,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "リスクアセスメント抽出例_250413.gdoc",
    reference: "リスクアセスメント抽出例_250413.gdoc",
    hazard: "設置不良が発生した場合に作業者が墜落する可能性がある。",
    riskReduction: "アンカーの強度や設置場所を事前に確認し、設置手順を遵守し、作業資格者が作業を行う。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-04",
    updatedAt: "2024-02-09"
  },
  {
    id: 22,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "20230321  漏電エラー（シャフト内工事）.pdf",
    reference: "20230321  漏電エラー（シャフト内工事）.pdf",
    hazard: "セーフティーブロックや工具などの重量物が落下し、作業者が手指を挟まれたり転倒したりする恐れがある。",
    riskReduction: "作業前に吊り具やチェーンブロックを点検し、適切な保護具を着用し、2人以上で作業し、作業エリアの安全を確保する。",
    measureType: "工学的対策",
    severity: 10,
    probability: 4,
    exposure: 4,
    riskScore: 18,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 13,
    riskLevelAfter: "IV",
    createdAt: "2024-02-05",
    updatedAt: "2024-02-10"
  },
  {
    id: 23,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LC手順書.pdf",
    reference: "LC手順書.pdf",
    hazard: "高所や開口部での作業中に墜落や工具・部材の落下、ロープの巻き込みや絡まりが発生する可能性がある。",
    riskReduction: "安全帯や保護具を着用し、足場や手摺、安全ネットを設置し、ロープの点検と正しい取り扱い、合図や声掛けを徹底する。",
    measureType: "工学的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-06",
    updatedAt: "2024-02-11"
  },
  {
    id: 24,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "リスクアセスメント抽出例_250413.gdoc",
    reference: "リスクアセスメント抽出例_250413.gdoc",
    hazard: "アンカーポイントの強度が不足している場合に墜落事故が発生する可能性がある。",
    riskReduction: "設計基準に基づいてアンカーポイントの強度を確認し、必要に応じて補強や交換を行い、点検記録を作成する。",
    measureType: "設計時対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 13,
    riskLevelAfter: "IV",
    createdAt: "2024-02-07",
    updatedAt: "2024-02-12"
  },
  {
    id: 25,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LS10-F03R-LC20210402-R0　施工手順書　キオクシア四日市（Y7_1期高揚程VC）_1.pdf",
    reference: "LS10-F03R-LC20210402-R0　施工手順書　キオクシア四日市（Y7_1期高揚程VC）_1.pdf",
    hazard: "高所作業中に作業者が墜落・転落したり、工具や部材が落下する危険がある。",
    riskReduction: "安全帯や親綱を使用し、手摺や安全ネットを設置し、合図や声掛けを徹底し、工具落下防止措置を講じる。",
    measureType: "工学的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-08",
    updatedAt: "2024-02-13"
  },
  {
    id: 26,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "H鋼材の表面に油分や水分が付着している場合、作業者が滑って転倒する可能性がある。",
    riskReduction: "作業前にH鋼材の表面を清掃し、滑り止めマットを敷設する。",
    measureType: "工学的対策",
    severity: 6,
    probability: 4,
    exposure: 4,
    riskScore: 14,
    riskLevel: "IV",
    severityAfter: 6,
    probabilityAfter: 1,
    exposureAfter: 4,
    riskScoreAfter: 11,
    riskLevelAfter: "III",
    createdAt: "2024-02-09",
    updatedAt: "2024-02-14"
  },
  {
    id: 27,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "セーフティーブロックの取付け位置が不適切な場合、落下時に十分な制動効果が得られない可能性がある。",
    riskReduction: "取付け位置を事前に検討し、メーカーの推奨位置に従って設置する。",
    measureType: "設計時対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 2,
    riskScoreAfter: 15,
    riskLevelAfter: "IV",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15"
  },
  {
    id: 28,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "作業中に周囲の作業者と接触し、バランスを崩して墜落する恐れがある。",
    riskReduction: "作業範囲を明確に区分し、同時作業を制限する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 4,
    exposure: 4,
    riskScore: 18,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 3,
    riskScoreAfter: 16,
    riskLevelAfter: "IV",
    createdAt: "2024-02-11",
    updatedAt: "2024-02-16"
  },
  {
    id: 29,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "セーフティーブロックのワイヤーが鋼材の角部で損傷し、落下防止機能が低下する可能性がある。",
    riskReduction: "ワイヤーの通過経路に保護材を設置し、定期的にワイヤーの損傷を点検する。",
    measureType: "工学的対策",
    severity: 10,
    probability: 4,
    exposure: 4,
    riskScore: 18,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 2,
    riskScoreAfter: 13,
    riskLevelAfter: "IV",
    createdAt: "2024-02-12",
    updatedAt: "2024-02-17"
  },
  {
    id: 30,
    work: "セーフティーブロックの取付け",
    workElement: "４FL下部H鋼材にセーフティーブロック(20M)を2箇所に取付ける",
    knowledgeFile: "LLMによる生成",
    reference: "LLMによる生成",
    hazard: "長時間の高所作業により作業者が疲労し、注意力が低下して事故が発生する可能性がある。",
    riskReduction: "作業時間を適切に区切り、定期的に休憩を取るようにする。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 3,
    exposureAfter: 3,
    riskScoreAfter: 16,
    riskLevelAfter: "IV",
    createdAt: "2024-02-13",
    updatedAt: "2024-02-18"
  },
  {
    id: 31,
    work: "引き寄せロープの設置",
    workElement: "引き寄せロープを開口部へ垂らす",
    knowledgeFile: "20160615  220棟6月10日発生_ファン巻き込まれ報告_20160615.pdf",
    reference: "20160615  220棟6月10日発生_ファン巻き込まれ報告_20160615.pdf",
    hazard: "ロープが下階の排気ファンに吸い込まれ、巻き込まれることで切断や飛散、作業者の巻き込まれ事故が発生する可能性がある。",
    riskReduction: "作業前に排気ファンを停止し、ファン停止を確認してから作業を行う。ロープの先端に重りを取り付けて直線的に下ろす。手順書に明記し、作業者に教育を実施する。",
    measureType: "管理的対策",
    severity: 10,
    probability: 6,
    exposure: 4,
    riskScore: 20,
    riskLevel: "IV",
    severityAfter: 10,
    probabilityAfter: 1,
    exposureAfter: 1,
    riskScoreAfter: 12,
    riskLevelAfter: "IV",
    createdAt: "2024-02-14",
    updatedAt: "2024-02-19"
  }
];